php-parallel-lint/PHP-Console-Highlighter

.travis.yml
build.xml

* The build was running on `xenial` which does not have `ant` installed by default, nor has PHP 5.4/5.5 images available.
Switching to the `trusty` distribution fixes this.
* Support for `sudo: false` has been removed from Travis over a year ago.
* Test against PHP 7.3, 7.4 and PHP `nightly` (= PHP 8), allowing the build against PHP 8 to fail for now.
The build script was still pointing to an outdated dependency.
Note: even though the PHPCS part of the build is failing, the build isn't being failed. I suspect this has to do with the ` failonerror="true"` attribute missing from the PHPCS command in the `build.xml` file.

Travis: fix build and other tweaks

---

README.md

Conform the `README.md` of `php-parallel-lint/PHP-Parallel-Lint`

Update the Composer installation command

---

composer.json

Non-dev:
* PHP Console Color has released version 0.3 in May.
I've set it to allow both `0.2` as well as `0.3` to prevent conflicts.
Packages which use this package which may have the Console Color package explicitly set as a requirement.
Dev:
* PHP Parallel Lint has released version 1.2.0 in April.
* PHP Var dump check has released version 0.4 in April.
I've set this one to be a flexible requirement to prevent having to update it on each new version.
* PHP_CodeSniffer has moved on a lot since version 1.5, so let's use a more recent one.
As it was, installing with PHP Console Color 0.3 was not allowed as Composer treats minors < 1.0 as majors.
So updating to that version requires an update to the `composer.json` requirements.
> For pre-1.0 versions it also acts with safety in mind and …

Composer: update allowed version for various dependencies

---

.travis.yml

Unless there is a specific reason to use `--prefer-source`, always use `--prefer-dist` for the `composer install` command to allow Travis to optimally use the caching feature.

Travis: improve caching between builds

---

README.md
composer.json
examples/snippet.php
examples/whole_file.php
examples/whole_file_line_numbers.php
src/Highlighter.php
tests/HighlighterTest.php

The `php-parallel-lint/php-console-color` package has tagged a new release.
The most notable change is the namespace update.
This updates the PHP Console Highlighter package to use the new version of PHP Console Color.
Refs:
* https://github.com/php-parallel-lint/PHP-Console-Color/releases/tag/v1.0

Use PHP Console Color to version 1.0

---

build.xml
phpunit.xml.dist

Move the CLI arguments which can be placed in the configuration file to the configuration file and removed them from the Ant build configuration.

PHPUnit: improve configuration

---

src/Highlighter.php
tests/HighlighterTest.php

> Namespaced names are now represented using the `T_NAME_QUALIFIED` (`Foo\Bar`), `T_NAME_FULLY_QUALIFIED` (`\Foo\Bar`) and `T_NAME_RELATIVE` (`namespace\Foo\Bar`) tokens. `T_NS_SEPARATOR` is only used for standalone namespace separators, and only syntactially valid in conjunction with group use declarations.
Ref: https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.tokenizer
This commit:
* Adds recognition for the new PHP 8.0 tokens for namespaced names and highlights these as `TOKEN_DEFAULT`, same as a non-namespaced `T_STRING` name.
* Adjusts the new unit tests to document the different highlighting between PHP < 8.0 and PHP 8.0+.
I've chosen not to make force the same highlighting across versions, but to let the highlighting respect the different …

PHP 8.0: handle changed tokenization of namespaced names

---

.gitattributes
.gitignore
build.xml
phpcs.xml.dist

* PHPCS: add a PHPCS configuration file containing all the common command-line parameters.
This file will be automatically picked up by PHPCS and can be overruled locally by a `[.]phpcs.xml` file.
Includes downgrading the cyclomatic complexity error to a warning.
* Ant: remove the configuration CLI arguments which are now contained in the `phpcs.xml.dist` file from the `build.xml` task configuration.
* Ant: add a CLI argument which will ignore CS warnings when determining the exit code, but will still _show_ warnings in the report.
Using this will also allow for enabling `failonerror` for the build step.
* Git: Add the `phpcs.xml.dist` file to the `.gitattributes` file to be ignored when packaging a release.
* Git: Add the potential local overload files to the `.gitignore` file.

PHPCS: various improvements

---

.github/workflows/cs.yml
.github/workflows/test.yml

Previously, in Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned on (as it was for most repos), any still running builds for the same branch would be stopped in favour of starting the build for the newly pushed version of the branch.
To enable this behaviour in GH Actions, a `concurrency` configuration needs to be added to each workflow for which this should applied to.
More than anything, this is a way to be kind to GitHub by not wasting resources which they so kindly provide to us for free.
Refs:
* https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
* https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
Follow up on #24 …

GH Actions: various updates / PHP 8.1 should no longer be allowed to fail

---

CHANGELOG.md

This helps to:
1. Keep the changelog readable when editing the markdown and
2. Removes the need to duplicate the links to contributors all over the place.
* The PHP 8.0 tokenization change is a functional fix.
* The dependency change from #12 only affects dev dependencies (as Console Color was updated again later in #17).

Changelog: improve maintainability

---

.github/workflows/cs.yml
composer.json
examples/snippet.php
examples/whole_file.php
examples/whole_file_line_numbers.php
phpcs.xml.dist
src/Highlighter.php
tests/HighlighterTest.php

* Composer: require `php-parallel-lint/php-code-style` at 2.0 or higher.
* Composer: remove the requirement for PHPCS. This will now be inherited from the code style repo.
* Scan all PHP files, not just the file in `src` for improved consistency across the code base, but exclude the `vendor` and the `build` (code coverage) directories.
* Enable parallel scanning for faster results.
* Use the ruleset from PHP-Code-Style by name.
* Set the `testVersion` for use with PHPCompatibility.
* Exclude the `LineLength` sniff for the tests.
* Include minimal documentation in the ruleset.
Fix up the issues which will be flagged by PHP-Code-Style 2.0 and explicitly ignore a couple of (non-)issues.
Includes no longer allowing warnings in the GH Actions build.
Rewrite the method to use predefined token …

Use PHP-Code-Style 2.0 

---

.github/workflows/test.yml
composer.json
phpcs.xml.dist
src/Highlighter.php

As Parallel Lint supports PHP 5.3 again since [PR 51](https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/51), it would be helpful for the Highlighter repo to also support PHP 5.3.
Now [PHP-Console-Color 1.0.1](https://github.com/php-parallel-lint/PHP-Console-Color/releases/tag/v1.0.1) has been released, support for PHP 5.3 can be restored for this repo as well.
This restores the PHP 5.3 minimum version along the same lines as before the version drop in 02b6aa6ea32b14fc15285b17babc3f10857bfb96
The PHP 5.3.2 minimum is in-line with the PHP Console Color minimum version for PHP 5.3.
Includes:
* Enabling a build against PHP 5.3 in the GH Actions workflow.
* Adjusting the `testVersion` for the PHPCompatibility checks to `5.3-` (5.3 and higher).

Bring back support for PHP 5.3

---

.github/workflows/test.yml
composer.json
phpunit.xml.dist
tests/TokenizeTest.php

This is a first PR in a series to improve the tests and test coverage for this package.
The PR will probably be easiest to review by looking at the commits individually.
Notes:
* All previously existing test cases, still exist.
* The additional new tests _document_ the existing functionality. No changes were made to the functionality of the package.
... as PHPUnit < 5.7.21 doesn't contain the forward compatibility layer with namespaced classes.
* Add more detailed basic test configuration
* Unless `junit` is used somewhere, generating this report for code coverage is unnecessary.
* Generating the text report, however, is useful.
Realistically, all tests in the `HighligherTest` file are testing the handling of various token types and only incidentally testing the rest of the logic of the …

Tests: improve existing tests

---

src/Highlighter.php
tests/GetCodeSnippetTest.php
tests/HighlighterTestCase.php
tests/TokenizeTest.php

... from which all test classes should extend and which contains the `getConsoleColorMock()` method to prevent having to duplicate it in multiple places.
The method has been adjusted to be slightly more flexible for re-use, in that the `$withTheme` parameter can be used to determine whether the ConsoleColor class should behave as if themes have been registered or not.
These tests also test the `private` `getHighlightedLines()`,  `splitToLines()` and `lineNumbers()` methods and the data sets in the data provider have been set up to ensure those methods are tested thoroughly.
When a code snippet in the middle of code is retrieved, the target snippet length calculation `$length = $linesAfter + $linesBefore + 1;` functions correctly, displaying the target line in the middle, padded by x …

Tests: introduce base HighlighterTestCase, dedicated tests for the getCodeSnippet() + two bug fixes

---

.github/workflows/cs.yml
.github/workflows/test.yml

Fixes a wrong variable which would cause all builds branched off from the same branch `master` to be cancelled whenever a new branch was pushed, while the build cancelling should only act on a new push for the _actual_ branch pushed.

GH Actions: fix build cancelling

---

tests/GetWholeFileTest.php

These tests also test the `private` `getHighlightedLines()`,  `splitToLines()` methods and - in part - the `lineNumbers()` method.

Tests: add dedicated tests for the `getWholeFile[WithLineNumbers]()` methods

---

CHANGELOG.md

* Updated the changelog to include all changes currently merged and in the [1.0.0 milestone](https://github.com/php-parallel-lint/PHP-Console-Highlighter/milestone/1).
* Simplified the changelog for the non-user facing changes.
Note: PR #40 is not currently included in the changelog and is not a user-facing change, so can be moved to the next milestone/release.

Release version 1.0.0

---

.github/workflows/cs.yml

If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.

GH Actions: harden the workflow against PHPCS ruleset errors

---

.github/workflows/cs.yml
.github/workflows/test.yml

PHP 8.2 has been released today :tada: and the `setup-php` action has announced support for PHP 8.3, so adding PHP 8.3 to the matrix and no longer allowing PHP 8.2 to fail the build.
Builds against PHP 8.3 are still allowed to fail for now.
Includes minor tweak setting PHP to `latest` for tasks where the PHP version isn't that relevant.

GH Actions: update PHP versions in workflows

---

.github/workflows/test.yml

The `coverallsapp/github-action` action runner has (finally) created a named branch for the 1.x series, so let's use that.
Ref: coverallsapp/github-action#100
PHP-Coveralls 2.6.0 has just been released and includes a fix for the last known PHP 8.x issue.
This means that it should now be safe to install php-coveralls on PHP 8.x and upload from there, which means we now only need the work-around for the PHP version when on PHP < 5.5 (as Coveralls v1 does not work with GH Actions).
Ref:
* https://github.com/php-coveralls/php-coveralls/releases/tag/v2.6.0

GH Actions: update for php-coveralls 2.6.0 

---

composer.json

The Package author still only mentioned "Jakub Onderka", while in reality other contributors should get credit for the work they have put in.
This is a relatively simple way to provide better credits.

Composer: give credit where credit is due

---

.gitattributes
.github/workflows/test.yml
.gitignore
composer.json
phpunit10.xml.dist
tests/ColorLinesTest.php
tests/GetCodeSnippetTest.php
tests/GetWholeFileTest.php
tests/TokenizeTest.php

As of PHPUnit 10, data providers are (again) expected to be `static` methods.
This updates the test suite to respect that.
Includes removing the use of `$this` from select data providers.
Refs:
* sebastianbergmann/phpunit@9caafe2
* sebastianbergmann/phpunit#5100
The PHPunit configuration file specification has undergone changes in PHPUnit 9.3, 10.0 and 10.1.
Most notably:
* In PHPUnit 9.3, the manner of specifying the code coverage configuration has changed.
* In PHPUnit 10.0, a significant number of attributes of the `<phpunit>` element were removed or renamed.
* In PHPUnit 10.1, there is another change related to the code coverage configuration + the ability to fail builds on deprecations/warnings/notices is brought back.
While the `--migrate-configuration` command can upgrade a …

PHPUnit: allow for PHPUnit 10 + add separate configuration

---

.github/workflows/test.yml

* Builds against PHP 8.4 are no longer allowed to fail.
* Add _allowed to fail_ build against PHP 8.5.
Ref: https://www.php.net/releases/8.4/en.php

GH Actions: PHP 8.4 has been released

---

tests/ColorLinesTest.php

Since PHP 8.1, calling the `Reflection*::setAccessible()` methods is no longer necessary as reflected properties/methods/etc will always be accessible. However, the method calls are still needed for PHP < 8.1.
As of PHP 8.5, calling the `Reflection*::setAccessible()` methods is now formally deprecated and will yield a deprecation notice, which will fail test runs. As of PHP 9.0, the `setAccessible()` method(s) will be removed.
With the latter in mind, this commit prevents the deprecation notice by making the calls to `setAccessible()` conditional.
Silencing the deprecation would mean, this would need to be "fixed" again come PHP 9.0, while the current solution should be stable, including for PHP 9.0.
Ref: https://wiki.php.net/rfc/deprecations_php_8_5#extreflection_deprecations

PHP 8.5 | Tests: prevent deprecation notice for Reflection*::setAccessible()
